### ISSUE TITLE
Robustly handle package schema breaking changes

### ISSUE THREAD

**Issue by candrewlee14** [candrewlee14/webman#34]
When package schema changes without backwards compatibility, `webman` should be able to notify the user that webman is out of date, and then install the package from a commit of `webman-pkgs` that was compatible (instead of erroring out trying to install an invalid new schema).

This could be something like a `compatibility.yml` in the root of `webman-pkgs`:
```yaml
webman_versions:
  - v0.8.0: [last compatible webman-pkgs commit SHA]
  - v0.9.0: [last compatible webman-pkgs commit SHA]
```
and an unspecified end would use the latest commit.
