### ISSUE TITLE
Binary link name replacement

### ISSUE THREAD

**Issue by candrewlee14** [candrewlee14/webman#35]
The problem occasionally comes up that a package `foo` distributes binaries inside a folder with the form `foo_blah_garbage.exe`. If we want the link binary to be called `foo.bat`, we need to do some replacing. This will resolve `cheat` and `gdu` binary name problems.

My idea currently is to allow something like this:
```yaml
os_map:
  macos:
    renames:
      - from: blah
        to: blah2
      - from: foo
        to: foo2
      - from: [ARCH]
      - to: ""
```
