### ISSUE TITLE
Add support for Pandoc

### ISSUE THREAD

**Issue by candrewlee14** [candrewlee14/webman#41]
Pandoc (https://github.com/jgm/pandoc/releases/tag/2.19.2) has a couple tricky cases that I don't think we can currently handle.

- Different arch map for each OS
- MacOS has universal binary, so it doesn't use arch

I think it might be good to allow a `filename_format_override` and `arch_map_override` within each OS in `os_map`.

**Comment by candrewlee14** [comment]
@jolheiser Any thoughts?

**Comment by jolheiser** [comment]
Hah, at this point we're getting close to just manually inputting every download URL it feels like.

I think your proposed solution sounds fine. It certainly could make for some complicated recipes, but I suppose that's inevitable given humans create release processes. 😅 

-----

As another alternative, what if we allowed for a new mapping of manual overrides altogether?

```yaml
override:
  - os: macos
    arch: amd64
    filename_format: pandoc-[VER]-macOS.zip
    is_raw_binary: false # Example
    bin_path: ... # Example
    extract_has_root: false # Example
```
I don't think this is any _less_ complicated, but it would be less nesting in YAML.
